using Clipper2Lib;

namespace RW.Toolpaths;

/// <summary>
/// Concentric-ring pocket-fill algorithm.
///
/// This is a 1-to-1 C# port of the <c>orbit-fill</c> function (aliased as <c>offset-kernel</c>)
/// functions <c>ring-collect</c> (offsetArray) and <c>tree-offset</c> (offsetTree).
///
/// <para>
/// The pocket is filled by repeatedly shrinking the boundary polygon inward
/// by one <paramref name="stepOver"/> per ring, using Clipper2's polygon-offset
/// engine, until no more rings fit.  Rings are then connected into a continuous
/// toolpath and optionally given a helical ramp lead-in.
/// </para>
/// </summary>
public static class OffsetFill
{
    // --- Public entry point ---------------------------------------------------

    /// <summary>
    /// Generates concentric-ring toolpaths for one pocket region.
    ///
    /// Mirrors <c>orbit-fill(n, t, e, i, r, s, o)</c> / <c>offset-kernel(n, t, e, i, rampingAngle, millingDirection)</c>.
    /// </summary>
    /// <param name="boundary">
    ///   Closed polygon rings that define the pocket.  Pass the outer boundary
    ///   as the first element; any holes as subsequent elements.
    ///   Coordinates are in workspace units (inches or mm).
    /// </param>
    /// <param name="depth">
    ///   Z depth of the fill (negative = into the material, e.g. <c>-0.1</c>).
    ///   Mirrors the <c>t</c> parameter.
    /// </param>
    /// <param name="zTop">
    ///   Safe Z entry height (e.g. <c>0.0</c>).  Used only when
    ///   <paramref name="rampingAngle"/> is non-zero.
    ///   Mirrors the <c>e</c> parameter.
    /// </param>
    /// <param name="stepOver">
    ///   Radial distance between adjacent rings (> 0).  Typically
    ///   <c>bitDiameter Ã— stepOverFraction</c>.
    ///   Mirrors the <c>i</c> parameter.
    /// </param>
    /// <param name="rampingAngle">
    ///   Lead-in ramp angle in radians.  <c>null</c> or <c>0</c> = plunge
    ///   vertically.  Mirrors the <c>r</c> parameter.
    ///   When non-zero the innermost ring gets a helical entry generated by
    ///   <see cref="RampUtils.LoopIn"/>.
    /// </param>
    /// <param name="millingDirection">
    ///   <c>"climb"</c>, <c>"conventional"</c>, or <c>null</c>.
    ///   When <c>null</c> the simple/fast code path is used (no tree needed).
    ///   Mirrors the <c>s</c> parameter.
    /// </param>
    /// <param name="maxIterations">
    ///   Maximum number of inward-offset rings.  Default 1 000.
    ///   Mirrors the <c>o</c> parameter.
    /// </param>
    /// <returns>
    ///   A list of polylines.  Each polyline is a sequence of
    ///   <see cref="Point3D"/> points at the given <paramref name="depth"/>.
    ///   Chain them together (with rapid moves between them) to mill the pocket.
    /// </returns>
    public static List<List<Point3D>> Generate(
        IEnumerable<IEnumerable<PointD>> boundary,
        double depth,
        double zTop,
        double stepOver,
        double?  rampingAngle     = null,
        string?  millingDirection = null,
        int      maxIterations    = 1_000)
    {
        long t0 = PerfLog.Start();
        if (depth > zTop)
            throw new ArgumentException(
                "depth must be â‰¤ zTop (deeper is more negative, e.g. depth=-0.1, zTop=0)");

        var paths = boundary
            .Select(r => r.ToList())
            .Where(r => r.Count >= 3)
            .ToList();

        // Make downstream offset/tree logic robust to overlapping or
        // self-intersecting caller input by canonicalizing into simple rings.
        paths = PathUtils.CanonicalizeRings(paths);

        if (paths.Count == 0)
            return new List<List<Point3D>>();

        bool hasDir = millingDirection is "climb" or "conventional";

        var result = (rampingAngle is null or 0) && !hasDir
            ? GenerateSimple(paths, depth, stepOver, maxIterations)
            : GenerateWithDirection(paths, depth, zTop, stepOver,
                                    rampingAngle ?? 0.0, millingDirection,
                                    maxIterations);

        PerfLog.Stop(
            "OffsetFill.Generate",
            t0,
            $"rings={paths.Count} output={result.Count} hasDirection={hasDir} ramp={rampingAngle ?? 0.0:F4}");

        return result;
    }

    // --- Simple case (no ramping, no milling-direction enforcement) -----------
    //

    private static List<List<Point3D>> GenerateSimple(
        List<List<PointD>> paths,
        double depth,
        double stepOver,
        int maxIterations)
    {
        long t0 = PerfLog.Start();
        var result = new List<List<Point3D>>();

        // Original boundary rings (offsetDistance = 0 â€” outermost cut)
        foreach (var ring in paths)
            result.Add(ToPath3D(ring, depth));

        // Iteratively shrink inward; each generation is one ring level
        var rings = OffsetArray(paths, -stepOver, maxIterations);
        foreach (var generation in rings)
            foreach (var ring in generation)
                result.Add(ToPath3D(ring, depth));

        result.Reverse();

        PathUtils.NearestNeighborSort(result);

        PerfLog.Stop(
            "OffsetFill.GenerateSimple",
            t0,
            $"input={paths.Count} output={result.Count}");

        return result;
    }

    // --- Complex case (milling direction and/or ramping) ---------------------
    //

    private static List<List<Point3D>> GenerateWithDirection(
        List<List<PointD>> paths,
        double depth,
        double zTop,
        double stepOver,
        double rampingAngle,
        string? millingDirection,
        int maxIterations)
    {
        long t0 = PerfLog.Start();
        var rootNodes = BuildPathTree(paths, offset: 0);

        // -- Flatten into groups: each group = [outer, hole1, hole2, ...]
        var groups = new List<List<List<PointD>>>();
        foreach (var rootNode in rootNodes)
        {
            var queue = new Queue<PathTreeNode>();
            queue.Enqueue(rootNode);
            while (queue.Count > 0)
            {
                var node  = queue.Dequeue();
                var group = new List<List<PointD>> { node.Points };
                foreach (var child in node.Children)
                {
                    group.Add(child.Points);
                    foreach (var grandchild in child.Children)
                        queue.Enqueue(grandchild);
                }
                groups.Add(group);
            }
        }

        // -- For each group build offsetTree, then harvest chains --------------
        var chains = new List<OffsetChain>(); // will be reversed at output

        foreach (var group in groups)
        {
            var offsetRoots = BuildOffsetTree(group, -stepOver, maxIterations);
            var treeQueue   = new Queue<PathTreeNode>(offsetRoots);

            while (treeQueue.Count > 0)
            {
                var node = treeQueue.Dequeue();

                // Orient the outermost ring for the required milling direction
                var oriented = PathUtils.OrientPath(
                    PathUtils.ToClipper(new[] { node.Points })[0],
                    millingDirection);

                // Start chain with this ring
                var chain    = new List<List<PointD>> { PathUtils.FromClipper(new Paths64 { oriented })[0] };
                var children = node.Children;

                // Chain single-child nodes into one continuous spiral
                while (children.Count == 1)
                {
                    var child       = children[0];
                    var childOriented = PathUtils.OrientPath(
                        PathUtils.ToClipper(new[] { child.Points })[0],
                        millingDirection);
                    chain.Insert(0, PathUtils.FromClipper(new Paths64 { childOriented })[0]);
                    children = child.Children;
                }

                // Smooth transitions: rebase each successive ring near the end
                // chain[0] is the innermost; chain[last] is the outermost
                if (chain.Count > 1)
                {
                    var prevEnd = chain[0][^1];
                    for (int b = 1; b < chain.Count; b++)
                    {
                        chain[b] = PathUtils.RebaseNear(chain[b], prevEnd);
                        prevEnd  = chain[b][^1];
                    }
                }

                // Add remaining children to the BFS queue
                foreach (var c in children)
                    treeQueue.Enqueue(c);

                chains.Insert(0, new OffsetChain(node.Offset, chain));
            }
        }

        // -- Convert chains to Point3D toolpaths -------------------------------
        var result = new List<List<Point3D>>();

        foreach (var chain in chains)
        {
            // Optional helical ramp lead-in into the innermost ring
            var allPoints = new List<Point3D>();

            if (rampingAngle > 0)
            {
                var rampPoints = RampUtils.LoopIn(chain.Paths[0], depth, zTop, rampingAngle);
                allPoints.AddRange(rampPoints);
            }

            // Flatten all rings in the chain into one continuous toolpath
            foreach (var ring in chain.Paths)
                allPoints.AddRange(ToPath3D(ring, depth));

            if (allPoints.Count > 0)
                result.Add(allPoints);
        }

        PerfLog.Stop(
            "OffsetFill.GenerateWithDirection",
            t0,
            $"input={paths.Count} chains={chains.Count} output={result.Count}");

        return result;
    }

    // --- offsetArray (ring-collect) -----------------------------------------------------

    /// <summary>
    /// Iteratively applies an inward polygon offset and collects the ring set
    /// produced at each step, stopping when no polygon survives.
    ///
    /// </summary>
    /// <param name="paths">
    ///   Input polygon rings in workspace coordinates.
    /// </param>
    /// <param name="delta">
    ///   Signed offset per step.  Negative = inward (shrink).
    ///   Pass <c>-stepOver</c> for pocket fill.
    /// </param>
    /// <param name="maxIterations">Max rings to generate.</param>
    /// <returns>
    ///   List where element [i] is the collection of rings at offset depth i+1.
    /// </returns>
    public static List<List<List<PointD>>> OffsetArray(
        IEnumerable<IEnumerable<PointD>> paths,
        double delta,
        int maxIterations = 1_000)
    {
        var result  = new List<List<List<PointD>>>();
        var current = PathUtils.Lighten(PathUtils.ToClipper(paths));

        while (maxIterations-- > 0)
        {
            var next = InternalInflate(current, delta);
            if (next.Count == 0) break;
            result.Add(PathUtils.FromClipper(next));
            current = next;
        }

        return result;
    }

    // --- pathTree (path-tree) and offsetTree (tree-offset) -----------------------------------

    /// <summary>
    /// Builds a nesting tree from a flat list of polygon rings by testing
    /// containment with <c>PointInPolygon</c>.
    ///
    /// </summary>
    public static List<PathTreeNode> BuildPathTree(
        IEnumerable<IEnumerable<PointD>> paths,
        int offset = 0)
    {
        var roots = new List<PathTreeNode>();
        foreach (var ring in paths)
        {
            var node = new PathTreeNode(ring.ToList(), offset);
            InsertIntoTree(roots, node);
        }
        return roots;
    }

    /// <summary>
    /// Builds an offset tree by repeatedly shrinking the input rings and
    /// inserting each new ring into the existing tree at the correct nesting
    /// level.
    ///
    /// </summary>
    public static List<PathTreeNode> BuildOffsetTree(
        IEnumerable<IEnumerable<PointD>> paths,
        double delta,
        int maxIterations = 1_000)
    {
        int depth   = 0;
        var roots   = BuildPathTree(paths, depth);
        var current = PathUtils.Lighten(PathUtils.ToClipper(paths));

        while (current.Count > 0 && depth++ < maxIterations)
        {
            var next = InternalInflate(current, delta);
            foreach (var intRing in next)
            {
                var node = new PathTreeNode(
                    PathUtils.FromClipper(new Paths64 { intRing })[0],
                    depth);
                if (InsertIntoTree(roots, node) == null)
                {
                    // InsertIntoTree always places the node; null means root-level insert
                }
            }
            current = next;
        }

        return roots;
    }

    // --- Tree-insertion helpers -----------------------------------------------
    //

    /// <summary>
    /// Inserts <paramref name="node"/> into the tree rooted at
    /// <paramref name="roots"/> at the correct nesting level.
    /// Returns the parent that accepted the node, or <c>null</c> if the node
    /// was added to <paramref name="roots"/> directly.
    ///
    /// </summary>
    private static PathTreeNode? InsertIntoTree(
        List<PathTreeNode> roots,
        PathTreeNode node)
    {
        // Condition A fires (root inside node): absorb root as node.Children, continue loop.
        // Condition B fires (node inside root): descend and return immediately.
        // The single-pass order is critical: after absorbing some roots (A), the loop
        // can still hit condition B for a later root â€” returning the node inside its parent.
        var intNode = node.GetIntPath();

        for (int i = roots.Count - 1; i >= 0; i--)
        {
            var root    = roots[i];
            var intRoot = root.GetIntPath();

            if (IsContainedIn(root, intNode))
            {
                node.Children.Add(root);                // t.children.push(n[e])
                roots.RemoveAt(i);                      // n.splice(e, 1)
                // loop continues â€” i decrements correctly since we removed at i
            }
            else if (IsContainedIn(node, intRoot))
            {
                return InsertUnder(root, node);
            }
        }

        roots.Add(node);
        return null;
    }
    private static PathTreeNode InsertUnder(PathTreeNode parent, PathTreeNode node)
    {
        var intNode = node.GetIntPath();

        //   while ((e = n.children.find(i => contains-node(i, t))) != null) n = e;
        // Descend to the deepest existing child that contains node.
        while (true)
        {
            PathTreeNode? containingChild = null;
            foreach (var child in parent.Children)
            {
                var intChild = child.GetIntPath();
                if (IsContainedIn(node, intChild))
                {
                    containingChild = child;
                    break;
                }
            }

            if (containingChild is null)
                break;

            parent = containingChild;
        }

        //   for each child r of n.children: if (contains-node(t, r)) move r under t
        for (int i = parent.Children.Count - 1; i >= 0; i--)
        {
            var child    = parent.Children[i];
            var intChild = child.GetIntPath();
            if (IsContainedIn(child, intNode))
            {
                node.Children.Add(child);
                parent.Children.RemoveAt(i);
            }
        }

        parent.Children.Add(node);
        return parent;
    }

    /// <summary>
    /// Returns <c>true</c> if <paramref name="inner"/>'s representative point
    /// is inside <paramref name="outerPath"/>.
    /// </summary>
    private static bool IsContainedIn(PathTreeNode inner, Path64 outerPath)
    {
        if (inner.Points.Count == 0 || outerPath.Count == 0) return false;
        var p = inner.GetIntPath()[0];
        return PathUtils.PointInPolygon(p, outerPath);
    }

    // --- Core Clipper2 inward-offset primitive --------------------------------
    //
    //       -> internal inflate with project scale and polygon end type
    //
    // ring-collect/tree-offset call inflatePaths(..., JoinType.Square, EndType.Polygon).

    private static Paths64 InternalInflate(Paths64 paths, double delta)
    {
        var scaled = Clipper.InflatePaths(
            paths,
            delta * PathUtils.Scale,   // delta already in workspace units; scale up
            JoinType.Square,
            EndType.Polygon);

        scaled = PathUtils.Lighten(scaled);

        // Clipper2 paths are implicitly closed; we add the explicit closing
        var result = new Paths64();
        foreach (var ring in scaled)
        {
            if (ring.Count == 0) continue;
            var closed = new Path64(ring) { ring[0] };
            result.Add(closed);
        }
        return result;
    }

    // --- Helpers --------------------------------------------------------------

    private static List<Point3D> ToPath3D(IEnumerable<PointD> ring, double z)
        => ring.Select(p => new Point3D(p.x, p.y, z)).ToList();

    // --- Internal record ------------------------------------------------------

    /// <summary>Holds a chained group of rings from the offset tree.</summary>
    private sealed class OffsetChain
    {
        public int Offset { get; }
        /// <summary>
        /// Ordered list of rings.  [0] = innermost ring, [^1] = outermost.
        /// </summary>
        public List<List<PointD>> Paths { get; }

        public OffsetChain(int offset, List<List<PointD>> paths)
        {
            Offset = offset;
            Paths  = paths;
        }
    }
}


